### ISSUE TITLE
Support __text/__value custom display query variables

### ISSUE THREAD

**Issue by njvrzm** [grafana/redshift-datasource#275]
**Is your feature request related to a problem? Please describe.**
Users migrating from the PostgreSQL datasource to the redshift datasource lose the ability to create query variables with custom display values using `__value` and `__text` columns as described in the [documentation](https://grafana.com/docs/grafana/latest/datasources/postgres/#query-variable).

See this [community thread](https://community.grafana.com/t/support-for-variables-text-and-value-redshift-plugin/114077/4) for an example.

**Describe the solution you'd like**
Redshift should support this feature to ease migration.

**Comment by StephenKing** [comment]
Thanks @njvrzm for filing the issue in my name.

If someone can give me a pointer, how this functionality can be added, I can try to file a PR.

Without this, dashboards variables are significantly less comfortable (users now have to enter the customer ID to filter for, instead of previously the ability to select based on the name of the customer) from a query variable.

**Comment by sarahzinger** [comment]
relates to https://github.com/grafana/athena-datasource/issues/286

**Comment by StephenKing** [comment]
Indeed, using `text` and `value` instead of `__text` and `__value` works.

**Comment by sarahzinger** [comment]
Just a heads up this is still broken, see discussion here: https://github.com/grafana/athena-datasource/issues/286

**Comment by idastambuk** [comment]
The use of text and value variables was misleading in the Grafana docs. We have [updated](https://github.com/grafana/redshift-datasource/pull/286) the Redshift docs recently - tldr this is supported with `text` and `value` variables instead of `__text` and `__value`.
