### ISSUE TITLE
Getting "Error updating options: unable to get default db connection" when switching data source in the default dashboard

### ISSUE THREAD

**Issue by grayhemp** [grafana/redshift-datasource#98]
**What happened**:

I added 2 data sources using the "Access & secret key" auth provider. Switching the data source on the dashboard was working fine. However, after adding the third data source using the "Workspace IAM Role" auth provider, when I was trying to select any of the first 2 data sources in the dashboard, I was getting an error "Error updating options: unable to get default db connection". Selecting the third data source was working fine.

**What you expected to happen**:

The first 2 data sources continue working after the third one was added. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Add first 2 data sources using the "Access & secret key" auth provider.
2. Add the 3rd data source using the "Workspace IAM Role" auth provider.
3. In the dashboard, try to switch between data sources.

**Environment**:
- Grafana version: Amazon Managed Grafana, 8.2.2

**Comment by andresmgot** [comment]
I'm able to reproduce this. _working in a fix_

**Comment by andresmgot** [comment]
I have just released a new version with the fix for this https://github.com/grafana/redshift-datasource/releases/tag/v1.0.1

A workaround for this issue is to just restart Grafana (but that's not an option for AMG). I guess the new version will be included in the next AMG deployment, right @mhausenblas ?

Thanks for filling the issue!
